# Generated by Django 2.2 on 2019-05-09 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190508_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apprequest',
            name='link',
        ),
    ]
