# Generated by Django 2.2 on 2019-05-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_apprequest_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprequest',
            name='link',
            field=models.URLField(default='http://uberdock.herokuapp.coms'),
        ),
    ]
