# Generated by Django 2.2 on 2019-05-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_apprequest_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprequest',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
